# Site settings
baseurl: "/teaching/publishing-dh.2016"
url: "http://jasonheppler.org/teaching/publishing-dh.2016"
source: source
destination: public

# Build settings
gems: 
  - jekyll-pandoc
markdown: pandoc
pandoc:
  extensions:
    - smart
permalink: pretty
lsi: false

# Draft or not?
draft: true

# Course information
title: "Design and Digital Scholarship Publishing"
course_catalog: 
course_credithours: 2
course_department: Humanities+Design
course_university: Stanford University
course_meetingtime: "Wednesdays, 1:00 to 3:00 p.m."
course_number: "DLCL 202"
course_room: "CESTA, 4th floor of Wallenberg Hall"
course_semester: "Spring 2016"
# course_blog: 
instructor_email: jheppler@stanford.edu
instructor_name: Nicole Coleman and Jason Heppler
instructor_office: "Building 200, Rm. 122 (Jason); CESTA (Nicole)"
instructor_officehours: Office hours by appointment
instructor_website: http://jasonheppler.org
